import Land from "./LandPageHeadStyle";
import LogoStyle from "./LandPageLogo";
import LandPageStyle from "./LandStyle";
import Button from "./Button";
import TeacherPageStyle from "./TeacherPageStyle";
import TeacherHead from "./TeacherHead";
import LogoPagesStyle from "./PagesLogo";
import BodyTeacher from "./BodyTeacher";
import BottomUL from "./BottomUL";
import Box from "./Box";
import DisplayRowCenter from "./DisplayRowCenter";
import ScheduleStyle from "./ScheduleStyle";
import DayStyle from "./DayStyle";
import BtnNonStyle from "./BtnNonStyle";
import PageInsideBox from "./PageInsideBoxStyle";
import LinkStyle from "./LinkStyle";
export {Land, LogoStyle, LandPageStyle, Button,TeacherPageStyle,TeacherHead, LogoPagesStyle,BodyTeacher, BottomUL, Box, DisplayRowCenter, ScheduleStyle, DayStyle, BtnNonStyle,PageInsideBox, LinkStyle};