import Land from "./LandPageHeadStyle";
import LogoStyle from "./LandPageLogo";
import LandPageStyle from "./LandStyle";
import Button from "./Button";
import TeacherPageStyle from "./TeacherPageStyle";
import TeacherHead from "./TeacherHead";
import LogoPagesStyle from "./PagesLogo";
import BodyTeacher from "./BodyTeacher";
import BottomUL from "./BottomUL";
import Box from "./Box";
import DisplayRowCenter from "./DisplayRowCenter";
export {Land, LogoStyle, LandPageStyle, Button,TeacherPageStyle,TeacherHead, LogoPagesStyle,BodyTeacher, BottomUL, Box, DisplayRowCenter};